services:
  api:
    container_name: api-node
    image: node:20-alpine3.18
    working_dir: /usr/src/app
    restart: always
    command: sh -c "apk --no-cache add curl && npm install && npm install -G dotenv-cli@7.3.0 && npm start || tail -f /dev/null"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/coverage
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=docker
      - PORT=3001
      - SECRET_TOKEN=bhdsdfBF#OBHpibPIB#hNVF#BIBPb3I%opGxsddswaqB%#dsfds/*-/*-+
      - DB_NAME=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER_NAME=postgres
      - DATABASE_PASSWORD=docker
      - DATABASE_NAME=personal-finance-manager
    depends_on:
      - db

  db:
    container_name: postgres-container
    image: postgres:15
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=personal-finance-manager
